[workspace]
resolver = "2"
members = ["src-tauri"]
default-members = ["src-tauri"]

[workspace.package]
edition = "2021"
rust-version = "1.77"
authors = ["Henrique Pereira Martins"]
license = "Proprietary"
repository = "https://github.com/henriquepm/papering"

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "warn"
unused_must_use = "deny"

[workspace.lints.clippy]
needless_pass_by_value = "warn"
redundant_clone = "warn"

[profile.release]
panic = "abort"
codegen-units = 16
lto = "thin"
opt-level = "s"
strip = true
incremental = false
